CREATE TABLE IF NOT EXISTS application_collections (
  name VARCHAR(64) PRIMARY KEY,
  data_json LONGTEXT NOT NULL,
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
    ON UPDATE CURRENT_TIMESTAMP(3),
  CHECK (JSON_VALID(data_json))
);
